#!/usr/bin/env bash
#send new file to remote host}
if [ $# -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ $# -eq 3 ]
#$1 = path, $2 = ip address, $3 = username
then
    scp -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
fi
