#!/usr/bin/env bash
#install nginx and redirect to CADO video
new_string="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=L3G1UX_eJV0&t=758s;\n\t}\n"
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=L3G1UX_eJV0&t=758s permanent;" /etc/nginx/sites-available/default
service nginx start
