#!/usr/bin/env bash
#install nginx and add new header HTTP
sudo apt-get -y update
sudo apt-gey -y install nginx
sudo sed -i "26i add_header X-Served-By \$hostname;" /etc/nginx/nginx.conf
sudo service nginx start
sudo service nginx restart
