#!/usr/bin/env bash
#configures haproxy
CONF="\
frontend striker_balancer
    bind *:80
    mode http
    default_backend striker

backend striker
    balance roundrobin
    server 1264-web-01 35.229.101.127:80 check
    server 1264-web-02 34.224.31.196:80 check
"
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo echo "ENABLED=1" >> /etc/default/haproxy
sudo echo "$CONF" >> /etc/haproxy.cfg
sudo service haproxy start
