#!/usr/bin/env bash
#process an PID file 
trap "echo I hate the kill command; /var/run/holbertonscript.pid; exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm /var/run/holbertonscript.pid" SIGQUIT
echo $$ > /var/run/holbertonscript.pid
while :
do
    echo "To infinity and beyond"
    sleep 2
done
