#!/usr/bin/env bash
#process an PID file
#sigterm 15 / sigint 2/ sigquit 3
echo "$$" > /var/run/holbertonscript.pid
trap "echo I hate the kill command; rm /var/run/holbertonscript.pid; exit" 15
trap "echo Y U no love me?!" 2
trap "rm /var/run/holbertonscript.pid; exit" 3
while :
do
    echo "To infinity and beyond"
    sleep 2
done
