#!/usr/bin/env bash
#say good an bad luck how in china
i=0
while [ $i -lt 10 ]; do
    if [ $i == 7 ]; then
	echo "good luck"
    elif [ $i == 3 ]; then
        echo "bad luck"
    else
	echo "Holberton School"
    fi
    (( i++ ))
done
