#!/usr/bin/env bash
i=1
while [ $i -le 20 ]; do
    echo $i
    case $i in
	4)
	    echo "bad luck from china"
	    ;;
	9)
	    echo "bad luck from china"
	    ;;
	17)
	    echo "bad luck from china"
	    ;;
	esac
    (( i++ ))
done
