#!/usr/bin/env bash
#Running nginx as nginx user
sudo pkill apache2
sudo chmod 777 /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
sudo sed -i "s/#user.*/user nginx/" /etc/nginx/nginx.conf
sudo -u nginx service nginx start
